version: "3.8"
services:
  frontend:
    container_name: data-input-mvp
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/app/node_modules" # the build stage creates a node_modules directory in the container, but at runtime it will be overwritten by the host directory. To prevent this, we need an anonymous volume
      - "./frontend/:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
