spring:
  main:
    banner-mode: "OFF"
  datasource:
    username: simple_report_app
    password: api123
    url: jdbc:postgresql://localhost:${SR_DB_PORT:5432}/simple_report
  jpa:
    properties:
      hibernate:
        default_schema: simple_report
  liquibase:
    user: simple_report_migrations
    password: migrations456

---
spring:
    profiles: cloud
    datasource:
        username: ${cloud.services.postgresql.credentials.username}
        password: ${cloud.services.postgresql.credentials.password}
        url: jdbc:postgresql://${cloud.services.postgresql.credentials.host}:${cloud.services.postgresql.credentials.port}/${cloud.services.postgresql.credentials.name}
    liquibase:
        user: ${cloud.services.postgresql.credentials.username}
        password: ${cloud.services.postgresql.credentials.password}
