spring:
  profiles.include: no-security
  liquibase:
    user: simple_report_migrations
    password: migrations456
  jpa:
    properties:
      hibernate:
        show_sql: true
        default_schema: simple_report
