# Smoketest/code lint checks for frontend package
name: Smoke Test Client

# Run this on pushes to any branch that change a frontend file or the workflow definition
on:
  push:
    branches: "**"
    paths:
      - "frontend/**"
      - .github/workflows/smoketest.yml

defaults:
  run:
    working-directory: frontend
jobs:
  smoketest:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
      - name: Node setup
        run: npm install
      - name: Test
        run: npm run-script test
  linter:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
      - name: Node setup
        run: npm install
      - name: Lint
        run: npm run-script lint
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json', 'frontend/package.json') }}
      - name: Node setup
        run: npm install
      - name: Build release
        run: npm run-script build
