name: Smoke Test Back-end API

# Run this on pushes to any branch that change a backend file or the workflow definition
on:
  push:
    branches: "**"
    paths:
      - "backend/**"
      - .github/workflows/smoketestBackend.yml

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Java Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('*.gradle', 'gradle/dependency-locks/*') }}
    - name: Run Java Tests
      run: ./gradlew test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Java Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('*.gradle', 'gradle/dependency-locks/*') }}
    - name: Run Java Tests
      run: ./gradlew checkstyleMain checkstyleTest
